### ISSUE TITLE
[Question] Installation of 21cmFast and 21CMMC

### ISSUE THREAD

**Issue by NGillet** [21cmfast/21CMMC#11]
I am trying to properly install 21cmFast and 21CMMC from this git repo : 
[21cmFast Collaboration](https://github.com/21cmfast) (which is the new long term project I think).

1) 21cmFast, following the doc:
        `> git clone https://github.com/21cmfast/21cmFAST.git` 
        `> conda env create -f environment_dev.yml -n myenv_21cmFast` 
        `> pip install -e .`
it works well, I can `import py21cmfast as p21` in this env (I didn't do other tests and sims for the moment)

2) 21CMMC:
here comes the confusion, should I create a new environment as it is said in the doc, or get into `myenv_21cmFast`  and there `pip install -e .` ?
What I try so far:
`pip install -e .` in `myenv_21cmFast` I get this error : `ERROR: error in 21CMMC setup command: "values of 'package_data' dict" must be a list of strings (got 'data/*')`.
so I edit the line 51 of setup.py: `package_data={"py21cmmc": ["data/*"]},` and it works (install and can import 21cmmc, no futher test) but I have no idea of the consequences of this change...

To conclude: 
i) is that the proper/correct way to install 21cmFast and 21CMMC ?
ii) how do I update my installation of 21cmFast and 21CMMC ? git pull, then update the env, then re-pip install for both code ?

**Comment by steven-murray** [comment]
Thanks for the report/question!

Yes, that is the new long-term repo, so thanks for installing from there.

As for the question of which environment to install into: that's up to you, largely. Either a new one or the same one as you made for 21cmFAST will be fine (if you use a new one, 21cmFAST should be automatically installed into that new one as well). The reason you might want to do two different envs is if you are developing and you really want to isolate the environments. Almost certainly, this won't be a problem and using just the one will be fine. 

It looks like that line in the setup.py file was just wrong. I *think* it should be `package_data={"py21cmmc": ["src/py21cmmc/data/*"]}`. You'll know if you got it right by installing the package and then doing an `ls` on your anaconda env (something like `ls <ANACONDA_BASE>/envs/myenv_21cmFast/lib/python3.7/site-packages/py21cmmc/data/`) and checking if the four files are in there. 

Can you check that, and make the change in a new branch, push and make a PR?

**Comment by dprelogo** [comment]
Only for 21CMMC:

There are also problems when trying to install it `pip` way.
Both `pip install 21CMMC` and `pip install 21cmFAST` give error
> Could not find a version that satisfies the requirement 21cmFAST/21CMMC (from versions: none)

Besides putting brackets in `package_data` mentioned above, what I've done to make it work is:
- delete `21cmFAST>=3.0.0dev` from `install_requires` in [setup.py](https://github.com/21cmfast/21CMMC/blob/master/setup.py)  (because of the mentioned error)
- correct the last line in  [requirements_dev.txt](https://github.com/21cmfast/21CMMC/blob/master/requirements_dev.txt) to `git+git://github.com/21cmFAST/21cmFAST#egg=21cmFAST`

After that if I run
`pip install -r requirements_dev.txt`
`pip install -e .`
everything builds fine.

**Comment by steven-murray** [comment]
Ah yes, we're waiting on 21cmFAST v3.0.0 to be released on PyPI (a few PRs to happen first), so I guess in the meantime, that is the appropriate fix. Thanks @dprelogo. Can you make a PR to that effect?

**Comment by steven-murray** [comment]
This was fixed in #13 . Please re-open if it's still not working for you!
