### ISSUE TITLE
[Question] py21cmfast functions/classes calls

### ISSUE THREAD

**Issue by dprelogo** [21cmfast/21CMMC#14]
Import/calls of some functions/classes don't work, for example (from tutorials):
`from py21cmmc import plotting` raises `ImportError` or `py21cmmc.initial_conditions(...)` raises `AttributeError`.

However, those are all also `py21cmfast` functionalities and can be used from there, but I'm not sure if they are exactly the same. Is this expected behaviour, or some initialisation is missing?

**Comment by steven-murray** [comment]
Ah, that's a problem with the docs, and an artifact of the move to this repository structure. In the previous 21CMMC, 21cmFAST was embedded and so everything was pulled from the same `py21cmmc` namespace. Now they are separate. If you have a spare moment, it would be great if you could move those parts of the docs to the `21cmFAST` repo. 

Is that something you're comfortable doing?

**Comment by dprelogo** [comment]
OK, thank you!
Those examples actually are part of `21cmFAST` docs (at least the ones I'm aware of), but as they included 21CMMC I thought it's more appropriate to ask here :)

**Comment by steven-murray** [comment]
Oh, if they're in the 21cmFAST docs, they should be changed to `from py21cmfast import plotting`!

**Comment by dprelogo** [comment]
Great, thanks! There are still some (minor) errors after doing so and those nice info messages about using cached files are not printed out.

**Comment by steven-murray** [comment]
Can you elaborate on what errors are remaining?

**Comment by dprelogo** [comment]
Sorry... when calling
```
from py21cmfast.cli import _query
_query(clear=True)
```
it breaks at
```
    552         else:
--> 553             direc = direc or path.expanduser(lib.config["boxdir"])
AttributeError: module 'py21cmfast.wrapper' has no attribute 'config'
```

**Comment by steven-murray** [comment]
Thanks! I'll look into it.
