### ISSUE TITLE
[BUG] Luminosity Function Bugs+questions

### ISSUE THREAD

**Issue by binnietom** [21cmfast/21CMMC#24]
Hey,

In line 950 of likelihood.py the def compute likelihood has 'return lnl' in the wrong indentation level. It is currently within the for loop, so it returns the lnl value for the first redshift only. 

Also within the lnl for the Luminosity function (line 946 of likelihood.py)', the lnl calculation returns a fiducially calculated luminosity (i think) rather than the data input one.
I'm giving it
'lnl += 0.5 *np.sum(
    (self.noise[i]["sigma"][:,1] - 10**model_spline(self.noise[i]["sigma"][:,0])) **2
     / self.noise[i]["sigma"][:,2] ** 2
)'
This should work given a cut for the magnitudes removing data for Muv<-20 has been made (I've just removed theses points from the input file (which is self.noise[redshift]["sigma"][Muv, phi, sigmaphi] format). 
I think (?) there should be a flag to tell it when to use data (like the line I provided above) or when to use the generated fiducial (like in line 946).

Finally I'm a bit confused by lines 571-575 in core.py  
Is this suppose to add some normal noise to the calculated LFs?
I get an error from the  ' scale = s(muv) ' argument  - I'm not sure what the standard deviation should be if adding normal noise onto these LFs?  
(Currently I'm just leaving this bit out).

Thanks,
Tom

**Comment by steven-murray** [comment]
Thanks @binnietom. 

I've fixed the returning lnl inside the loop problem in #22. As for your other questions, I'm not quite sure what you mean.

All subclasses of `LikelihoodBaseFile` (like `LikelihoodLuminosityFunction`) are able to receive a `datafile=` and `noisefile=` argument. In this case, the datafile should be a `.npz` file with `Muv` and `lfunc` arrays in it. The `self.data['lfunc'][i]` call in the `computeLikelihood` function should access that passed data, _if_ you passed a datafile. Otherwise, the "data" will be fiducial mock data. 

The `convert_model_to_mock()` method in `core.py` is supposed to take whatever the `Core` produces and turn it into that mock data -- in this case by adding Gaussian noise. What are you passing for `sigma` to make it break? And what is the associated error?

**Comment by binnietom** [comment]
Hi Steven,
Thanks for clarifying, I had been using it wrong here. 
I've been passing all the observed LF through the sigma param as well as the LF sigmas (hence my use rewrite using self.noise in my previous message). 

The error (copied below) isn't urgent as I've got a version working with Bouwens' data. It works if the sigma passed to the LF core is a constant, or an array, but fails whenever it is an array of an array (in my head this would be an array of sigma_phi values per Muv per redshifts, also shouldn't it need the Muv values to tell which errors are which? - unless it needs to be matched to the data input within the LF likelihood?). 

Cheers, Tom

```
Traceback (most recent call last):
  File "/home/tab216/21CMMC/src/py21cmmc/core.py", line 577, in convert_model_to_mock
    lfunc[i] += np.random.normal(loc=0, scale= s(muv), size=len(lfunc[i]))
TypeError: 'numpy.ndarray' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "2nd_21CMNest.py", line 191, in <module>
    chain = py21cmmc.mcmc.build_computation_chain(core, likelihood, params)
  File "/home/tab216/21CMMC/src/py21cmmc/mcmc.py", line 49, in build_computation_chain
    chain.setup()
  File "/home/tab216/21CMMC/src/py21cmmc/cosmoHammer/LikelihoodComputationChain.py", line 169, in setup
    cModule.setup()
  File "/home/tab216/21CMMC/src/py21cmmc/likelihood.py", line 497, in setup
    LikelihoodBaseFile.setup(self)
  File "/home/tab216/21CMMC/src/py21cmmc/likelihood.py", line 133, in setup
    simctx = self.chain.simulate_mock()
  File "/home/tab216/21CMMC/src/py21cmmc/cosmoHammer/LikelihoodComputationChain.py", line 78, in simulate_mock
    core.simulate_mock(ctx)
  File "/home/tab216/21CMMC/src/py21cmmc/core.py", line 176, in simulate_mock
    self.convert_model_to_mock(ctx)
  File "/home/tab216/21CMMC/src/py21cmmc/core.py", line 579, in convert_model_to_mock
    lfunc[i] += np.random.normal(loc=0, scale=s, size=len(lfunc[i])) 
  File "mtrand.pyx", line 1661, in mtrand.RandomState.normal
ValueError: scale < 0 
```

**Comment by steven-murray** [comment]
Thanks @binnietom, good to know it's basically working. It seems like what you're getting is saying that the sigmas that you're passing are sometimes less than zero (which wouldn't make sense, of course).

An array of arrays (shape `(len(redshifts), len(Muv))`) should work perfectly fine, as long as the sigmas are all positive. The `Muv` I refer to here is that of the _model_ (i.e. whatever is produced on every iteration), because this is what is used to produce a fiducial mock. 

You can also pass a list of functions of Muv which will be evaluated to be the sigmas. 

I will try to write some documentation for the class soon.

**Comment by binnietom** [comment]
Hi Steven, 

Now that I can install things (in most places) I've tried to follow your methodology for inputtign the luminosity function data.
I'm not sure if its a good idea to have a matrix with axes of redshifts and Muv (for lfuncs or sigmas) - unless I've misinterpreted what you intend (please reiterate if so).

The observational measurements at each redshift have different Muv values and a different number of them -leading to concatenation errors and when I try to format an .npz file in this way. 

I can't pad the matrix because it reads 0 or nan values into the likelihood calculation and crashes.
I could interpolate it to match the simulation but then the likelihood is no longer measured against raw data, which is what I would like. I would like the simulation to be measured at the observational Muv values per redshift.

Since the 21cm likelihood calculation is iterated per redshift (as with the lightcone chunks), can't the LF likelihood just have an .npz file per redshift? - that way the likelihood calculations follow the same methodology.
Thanks,
Tom

**Comment by steven-murray** [comment]
@binnietom ah yes, I understand your predicament. I *think* you can get around that fairly easily, by using multiple likelihoods (each one using a luminosity function with a single redshift). Would this work for you?

**Comment by binnietom** [comment]
Trying at the moment... 
e.g.
```
#z6
 core_lfz6 = py21cmmc.core.CoreLuminosityFunction( 
        redshift = 6,
        user_params =  core_21cm.user_params,
        flag_options = core_21cm.flag_options,
        sigma = 1.,   
    )
    likelihood_lfz6 = py21cmmc.likelihood.LikelihoodLuminosityFunction(
        datafile = 'LF_lfuncs_z6.npz',   #with Muv and lfuncs arrays
        noisefile = 'LF_sigmas_z6.npz',  #with sigma array
        simulate = False,  
    )

core = [core_lfz6]
likelihood = [likelihood_lfz6]
chain = py21cmmc.mcmc.build_computation_chain(core, likelihood, params) 
```

Seems to pass ok - will let you know how it turns out! 

Also I've picked sigma=1.  arbitrarily - do you have a choice for this sigma we can justify? (if not what would you recommend?)

Thanks, 
Tom

**Comment by binnietom** [comment]
I spoke to soon, I think I've found a bug for when 'simulate=True' 
(- still seems ok for simulate=False, but I'd like to plot the best fit LF when the runs finish)
The error I get is:

```
 File "/rdsgpfs/general/ephemeral/user/tab216/ephemeral/21CMMC/src/py21cmmc/mcmc.py", line 49, in build_computation_chain
    chain.setup()
  File "/rdsgpfs/general/ephemeral/user/tab216/ephemeral/21CMMC/src/py21cmmc/cosmoHammer/LikelihoodComputationChain.py", line 169, in setup
    cModule.setup()
  File "/rdsgpfs/general/ephemeral/user/tab216/ephemeral/21CMMC/src/py21cmmc/likelihood.py", line 150, in setup
    self._write_data()
  File "/rdsgpfs/general/ephemeral/user/tab216/ephemeral/21CMMC/src/py21cmmc/likelihood.py", line 197, in _write_data
    np.savez(fl, **d)
TypeError: savez() argument after ** must be a mapping, not str
```

After some grep-ing I'm pretty sure the `simctx = self.chain.simulate_mock()` object in likelihood.py isn't a dictionary (or whatever acts on it isn't producing a dictionary), but I'm a bit stuck after that.

**Comment by steven-murray** [comment]
Ah OK. I'll have a look at that, hopefully today, maybe tomorrow!

**Comment by binnietom** [comment]
Found a bug in the Luminosity function likelihood calculation at line 956 of likelihood.py

lnl += -0.5 * np.sum(
                (self.data["lfunc"][i] - model_spline(self.data["Muv"][i])) ** 2
                / self.noise[i]["sigma"] ** 2
            )

should be:

lnl += -0.5 * np.sum(
                (self.data[i]["lfuncs"] - model_spline(self.data[i]["Muv"])) ** 2
                / self.noise[i]["sigma"] ** 2
            )

**Comment by steven-murray** [comment]
Awesome -- can you make a PR fixing some of these things -- and add some tests? I can walk you through it if you like.

**Comment by qyx268** [comment]
how's this issue? I'm having difficulties using the LF likelihood... I'm not sure if I have the datafile or noisefile. Also is it true that we have to pass the core and likelihood for each redshifts now rather than giving an array of redshifts as in the tutorial?

**Comment by steven-murray** [comment]
There is a branch called `LF_likelihood_bug` which you'll require to get the LF to work well (and @binnietom is still working on some of the details). 

Actually you can do it either way: if you have a bunch of luminosity functions at different redshifts for which you want different UV-resolutions, you should pass multiple cores/likelihoods, one for each redshift. Otherwise, if the UV-resolution should be the same at all redshifts, you can pass it as an array of redshifts. 

The docstring in the branch should be a little clearer about how the input noisefile and datafile should be formatted now.

**Comment by andreimesinger** [comment]
hi @binnietom @steven-murray, could we PR this ASAP please? we have a project which requires some LF MCMCs and is otherwise close to finishing.  i don't really understand how come there is a bug when @BradGreig has run several MCMCs including LFs with the new version (i think...)

**Comment by steven-murray** [comment]
@andreimesinger sure thing. I think the bugs are less fundamental bugs and
more that sometimes the interface is surprising.
@binnietom: the current branch is working for you, right? If so, can you
make it a PR?
