### ISSUE TITLE
[BUG] Memory Leak

### ISSUE THREAD

**Issue by steven-murray** [21cmfast/21CMMC#4]
This is a copy/restatement of part of https://github.com/BradGreig/Hybrid21CM/issues/30.

**Describe the bug:**

@caw11 stated:

> Just to add to this, in case our prior ranges are equally flawed.

> I have some students running the higher parameterisation (i.e. that of Park+ 2018 but without spin temp) and are experiencing a similar problem. Our params dictionary looks like this:

> ```FitParams = dict(F_STAR10 = [-1.3, -3.0, 0.0, 0.1],
> ALPHA_STAR = [0.5, -0.5, 1.0, 0.05],
> F_ESC10 = [-1.0, -3.0, 0.0, 0.1],
> ALPHA_ESC = [-0.5, -1.0, 0.5, 0.05],
> M_TURN = [8.7, 8.0, 10.0, 0.1],
> t_STAR = [0.5, 0.0, 1.0, 0.05]).```

> With 8 threads the code consistently crashes after ~40 iteration with it sometimes returning the same exception as described above. However, they have observed that if they run in iterations batches of 30 continuing sampling, then it stalls much less regularly. I wonder if there might be a memory leak issue of some sort on top of the discontinuity issues in some regions of parameter space? Apologies if such a memory leak issue has already been raised elsewhere.

@BellaNasirudin added:
> I have been (still am) experiencing memory leak issue as well. I am using this version commit 450d096

> In my case, it seems to come from the storage module in 21cmmc since when I opted out of doing that, the code ran through perfectly fine and only used 100 GB. Of course, the downside is that I cannot analyse the walkers if there is something wrong with the MCMC and will have to run everything again.

> With the storage module included, I am using at least 915 GB so it's very computationally expensive.

**Expected behavior:**

That memory would not grow so large as to crash the system.

**Comment by steven-murray** [comment]
A fix was issued in 53b28c8c13a44b874f4ba9ee1a25539821e41627 which may have solved this issue. @caw11 can you confirm if your issue persists?

@BellaNasirudin have you found anything that alleviates the memory build-up?

**Comment by steven-murray** [comment]
@caw11 and @BellaNasirudin, I am going to close this issue for now, as a fix has been issued and no further errors have been reported. Feel free to re-open if you have had any more errors.

**Comment by binnietom** [comment]
Hi Steven, 
As requested attached* is the simplest run found with the memory leak. Every other parameter combination I have tried does also cause a leak but in the less expensive models (e.g. like this one with coeval cubes and no spin temperature) it can be run on higher memory machines - they get away with running all the samplers before crashing. It is the virtual memory which fills up (having watched it with the top command).   
The valgrind results from my desktop are:
[valgrind_origins.txt](https://github.com/21cmfast/21CMMC/files/3730807/valgrind_origins.txt)

* it wouldn't let me attach a .py so here it is in .txt .
[CosmoHammer_test.txt](https://github.com/21cmfast/21CMMC/files/3730788/CosmoHammer_test.txt)

Thanks,
Tom

**Comment by steven-murray** [comment]
I'm just going to simplify the script further here for ease-of-reference:

```python
import numpy as np
from py21cmmc import mcmc
import py21cmmc
print(py21cmmc.__version__)

location = 'cosmohammer_data'
model_name = 'SimpleTest'

core = py21cmmc.core.CoreCoevalModule( # All core modules are prefixed by Core* and end with *Module
    redshift = [7,8,9],          # Redshifts of the coeval fields produced.
    user_params = dict(       # Here we pass some user parameters. Also cosmo_params, astro_params and flag_options
        HII_DIM = 50,         # are available. These specify only the *base* parameters of the data, *not* the
        BOX_LEN = 125.0       # parameters that are fit by MCMC.
    ),
    regenerate=True          # Don't regenerate init_boxes or perturb_fields if they are already in cache.
)

datafiles = [ location + '/'+ model_name +'_mcmc_data_%s.npz'%z for z in core.redshift]

likelihood = py21cmmc.likelihood.Likelihood1DPowerCoeval(  # All likelihood modules are prefixed by Likelihood*
    datafile = datafiles,                   # All likelihoods have this, which specifies where to write/read data
    noisefile= None,                        # All likelihoods have this, specifying where to find noise profiles.
    logk=False,                             # Should the power spectrum bins be log-spaced?
    min_k=0.1,                              # Minimum k to use for likelihood
    max_k=1.0,                              # Maximum ""
    simulate = True,                        # Simulate the data, instead of reading it in.
                                            # will be performed.
)



chain = mcmc.run_mcmc(
    core, likelihood,        # Use lists if multiple cores/likelihoods required. These will be eval'd in order.
    datadir=location,          # Directory for all outputs
    model_name=model_name,   # Filename of main chain output
    params=dict(             # Parameter dict as described above.
        HII_EFF_FACTOR = [30.0, 10.0, 50.0, 3.0],
        ION_Tvir_MIN = [4.7, 4, 6, 0.1],
    ),
    walkersRatio=3,         # The number of walkers will be walkersRatio*nparams
    burninIterations=0,      # Number of iterations to save as burnin. Recommended to leave as zero.
    sampleIterations=400,    # Number of iterations to sample, per walker.
    threadCount=6,           # Number of processes to use in MCMC (best as a factor of walkersRatio)
    continue_sampling=False  # Whether to contine sampling from previous run *up to* sampleIterations.
)
```

**Comment by steven-murray** [comment]
Using the above script, but with threadCount=1 (and many fewer iterations), I get the following output from top (columns are VIRT, RES, %CPU, %MEM):

```
236644    38968     75.8      0.2     
251264    50472     90.9      0.3     
273796    66696     87.1      0.4     
318468    89768     90.6      0.6     
392924    112316    90.6      0.7     
522788    120692    100.0     0.7     
522788    128612    100.0     0.8     
522788    136268    100.0     0.8     
522788    143924    100.0     0.9     
522788    177188    96.8      1.1     
523296    211376    100.0     1.3     
523296    211632    96.9      1.3     
523432    212160    100.0     1.3     
713088    324096    96.9      2.0     
713352    402504    96.8      2.5     
713352    402504    100.0     2.5     
713484    403136    100.0     2.5     
650488    328080    100.0     2.0     
464924    155028    93.8      1.0     
403652    126072    96.8      0.8     
716128    186140    300.0     1.2     
716128    186140    96.9      1.2     
716404    187724    96.8      1.2     
767116    200716    187.1     1.2     
863868    187832    3.2       1.2     
767116    201468    200.0     1.2     
767116    201468    100.0     1.2     
767372    229008    100.0     1.4     
767372    229008    100.0     1.4     
767372    229076    100.0     1.4     
767116    229052    96.9      1.4     
767116    229052    103.2     1.4     
767116    229052    96.9      1.4     
767116    243564    103.2     1.5     
767116    243564    100.0     1.5     
767116    243564    96.9      1.5     
767116    244616    103.2     1.5     
767116    244616    96.9      1.5     
767116    244616    103.2     1.5     
767116    244616    96.9      1.5     
767116    244672    103.2     1.5     
767116    244672    96.9      1.5     
767116    244672    100.0     1.5     
767360    244672    100.0     1.5     
863868    187856    3.2       1.2     
767360    244672    96.9      1.5     
767360    244672    103.2     1.5     
772524    249940    96.9      1.5     
772524    249940    100.0     1.5     
772524    249940    100.0     1.5     
777688    249940    103.2     1.5     
777688    255220    100.0     1.6     
777688    255220    100.0     1.6     
777688    255220    96.9      1.6     
814100    286372    100.0     1.8     
814100    286372    100.0     1.8     
814100    286372    100.0     1.8     
814100    291652    96.9      1.8     
814100    291652    100.0     1.8     
814100    291652    100.0     1.8     
814100    291652    100.0     1.8     
6268      2332      3.2       0.0     
814100    291652    100.0     1.8     
814100    291652    93.5      1.8     
863868    187892    6.5       1.2     
814100    291652    103.2     1.8     
814100    291652    96.9      1.8     
814100    291652    100.0     1.8     
814100    291652    100.0     1.8     
814100    291652    100.0     1.8     
814100    291652    100.0     1.8     
814100    291652    100.0     1.8     
814100    291652    100.0     1.8     
814100    291652    100.0     1.8     
814100    291652    96.8      1.8     
814100    291652    100.0     1.8     
814100    291652    100.0     1.8     
818964    296404    103.2     1.8     
863868    187892    3.2       1.2     
818964    296404    100.0     1.8     
818964    296404    100.0     1.8     
824128    301420    96.9      1.9     
824128    301420    100.0     1.9     
824128    301420    100.0     1.9     
824128    301420    96.8      1.9     
863868    187904    3.2       1.2     
860536    332836    100.0     2.1     
860536    332836    100.0     2.1     
860536    332836    100.0     2.1     
860536    337852    96.9      2.1     
860536    337852    100.0     2.1     
860536    337852    100.0     2.1     
860536    337852    100.0     2.1     
860536    337852    100.0     2.1     
860536    337852    100.0     2.1     
860536    337852    96.8      2.1     
863868    187904    3.2       1.2     
860536    337852    103.2     2.1     
860536    337852    96.9      2.1     
860536    337852    100.0     2.1     
860536    337852    103.2     2.1     
860536    337852    100.0     2.1     
860536    337852    96.8      2.1     
860536    337852    103.2     2.1     
860536    337852    96.9      2.1     
860536    337852    93.5      2.1     
863868    187904    3.2       1.2     
860536    337852    100.0     2.1     
860536    337852    100.0     2.1     
860536    337852    103.2     2.1     
865396    342868    96.9      2.1     
865396    342868    100.0     2.1     
865396    342868    100.0     2.1     
870552    347884    100.0     2.2     
870552    347884    100.0     2.2     
870552    347884    100.0     2.2     
906960    379300    100.0     2.3     
863868    187904    3.2       1.2     
906960    379300    100.0     2.3     
906960    379300    100.0     2.3     
906960    384316    100.0     2.4     
906960    384316    96.9      2.4     
906960    384316    100.0     2.4     
906960    384316    103.2     2.4     
906960    384316    96.8      2.4     
906960    384316    100.0     2.4     
906960    384316    96.8      2.4     
6268      2332      3.2       0.0     
863868    187904    3.2       1.2     
906960    384316    96.9      2.4     
906960    384316    100.0     2.4     
906960    384316    103.2     2.4     
906960    384316    96.9      2.4     
906960    384316    100.0     2.4     
906960    384316    100.0     2.4     
906960    384316    103.2     2.4     
906960    384316    100.0     2.4     
906960    384316    96.8      2.4     
906960    384316    100.0     2.4     
863868    187904    3.2       1.2     
906960    384316    100.0     2.4     
906960    384316    100.0     2.4     
943068    415732    96.9      2.6     
943068    415732    100.0     2.6     
943068    415732    100.0     2.6     
943068    420484    103.2     2.6     
943068    420484    100.0     2.6     
943068    420484    100.0     2.6     
943068    420484    93.8      2.6     
863868    187904    3.1       1.2     
943068    420484    96.8      2.6     
943068    420484    103.2     2.6     
943068    420484    100.0     2.6     
943068    420484    96.8      2.6     
943068    420484    103.2     2.6     
943068    420484    96.9      2.6     
943068    420484    100.0     2.6     
943068    420484    100.0     2.6     
943068    420484    100.0     2.6     
949904    427348    100.0     2.6     
863868    187992    3.2       1.2     
949904    427348    96.8      2.6     
949904    427348    100.0     2.6     
949904    427348    103.2     2.6     
949904    427348    96.9      2.6     
949904    427348    100.0     2.6     
949904    427348    100.0     2.6     
949904    427348    100.0     2.6     
949904    427348    100.0     2.6     
949904    427348    96.8      2.6     
863868    187992    3.2       1.2     
953064    430516    100.0     2.7     
953064    430516    100.0     2.7     
953064    430516    100.0     2.7     
958220    435532    100.0     2.7     
958220    435532    96.8      2.7     
958220    435532    103.2     2.7     
963376    440812    100.0     2.7     
963376    440812    96.9      2.7     
963376    440812    100.0     2.7     
963376    440812    100.0     2.7     
863868    187992    6.5       1.2     
968532    445828    100.0     2.8     
968532    445828    100.0     2.8     
968532    445828    96.9      2.8     
973688    451108    100.0     2.8     
973688    451108    100.0     2.8     
973688    451108    100.0     2.8     
978844    456388    103.2     2.8     
978844    456388    103.2     2.8     
978844    456388    96.9      2.8     
983996    461404    90.6      2.9     
863868    187992    3.1       1.2     
983996    461404    103.2     2.9     
983996    461404    96.9      2.9     
983996    461404    100.0     2.9     
989152    466684    100.0     2.9     
989152    466684    100.0     2.9     
989152    466684    100.0     2.9     
994308    471700    103.2     2.9     
994308    471700    100.0     2.9     
994308    471700    100.0     2.9     
863868    187992    3.2       1.2     
999460    476980    93.8      2.9     
999460    476980    100.0     2.9     
999460    476980    103.2     2.9     
1004616   481996    96.8      3.0     
1004616   481996    100.0     3.0     
1004616   481996    100.0     3.0     
1009772   487276    103.2     3.0     
1009772   487276    100.0     3.0     
1009772   487276    100.0     3.0     
1014928   492292    93.5      3.0     
863868    187992    3.2       1.2     
1014928   492292    96.9      3.0     
1014928   492292    100.0     3.0     
1014928   492292    100.0     3.0     
1020076   497572    100.0     3.1     
1020076   497572    100.0     3.1     
1020076   497572    103.2     3.1     
1025232   502588    100.0     3.1     
1025232   502588    100.0     3.1     
1025232   502588    100.0     3.1     
863868    187992    3.2       1.2     
1030388   507868    96.8      3.1     
1030388   507868    100.0     3.1     
1030388   507868    100.0     3.1     
1035548   512884    100.0     3.2     
1035548   512884    100.0     3.2     
1035548   512884    100.0     3.2     
1040704   518164    100.0     3.2     
1040704   518164    96.9      3.2     
1040704   518164    100.0     3.2     
1045852   522124    96.8      3.2     
863868    187992    3.2       1.2     
1045852   523180    100.0     3.2     
1045852   523180    100.0     3.2     
1045852   523180    96.9      3.2     
1051008   528460    103.2     3.3     
1051008   528460    100.0     3.3     
1051008   528460    100.0     3.3     
1056164   533476    100.0     3.3     
1056164   533476    100.0     3.3     
1056164   533476    100.0     3.3     
1061320   538756    100.0     3.3     
863868    187992    3.2       1.2     
1061320   538756    96.9      3.3     
1061320   538756    100.0     3.3     
1066472   543772    100.0     3.4     
```

Overall, it _seems_ to be doing what we want... i.e. the memory rises and falls as each iteration passes. The virtual memory does increase overall, but it also drops when the memory drops.
I should mention that top is recording on a time cadence of 0.3 sec.

**Comment by steven-murray** [comment]
Letting it run for more iterations (still with a single thread) does show that there is a memory leak -- the percentage memory use almost monotonically increases. Strangely enough, every ~13 lines, it will print that the memory went down (to around 1%), but then the next line will begin again where it left off, instead of starting at the low memory value again. 

However, I'm also printing out a trace of the python objects in memory at each iteration, and this seems to be stable. So I presume the fault is in the C somewhere... (which is always frustrating....).

**Comment by binnietom** [comment]
This is exactly what I saw. If I can help out in any way let me know. 
For now, I've written a script that takes the output and resumes the run when it gets killed which sort of works! 

Thanks, Tom

**Comment by catherinewatkinson** [comment]
Just had a quick squizz. I can see an allocation in IonizationBox.c that is not being freed, it's only called if(INIT_ERFC_INTERPOLATION), so not sure it will be the cause of what Tom is seeing, but ultimately I imagine they need to be freed.

L120-121
        ERFC_VALS = calloc(ERFC_NUM_POINTS,sizeof(double));
        ERFC_VALS_DIFF = calloc(ERFC_NUM_POINTS,sizeof(double));

Also the allocs at L105 of SpinTemperatureBox.c for *box and *unfiltered_box don't seem to be freed anywhere I can see

Also appears to be no freeing of pid which gets allocated in, and returned from fn at L552 of UsefulFunctions.c (but this one is a little funky, so less sure this is a problem)
char * pid = malloc(12*sizeof(char));

**Comment by catherinewatkinson** [comment]
Also the allocs L105 in SpinTemperatureBox *box and *unfiltered_box don't seem to be freed anywhere I can see

**Comment by steven-murray** [comment]
@binnietom that is certainly suboptimal and we will definitely try to fix it properly!

Thanks @catherinewatkinson, I'll look through those things today as well. For now, here's the redacted output of valgrind run on the script I posted above, with a single thread. 
[valgrind.txt](https://github.com/21cmfast/21CMMC/files/3744846/valgrind.txt)

I removed all the bits that didn't seem to be about py21cmfast. 

I should note that if you want to run with valgrind (which I'm sure you do...), you should re-install `21cmFAST` with `DEBUG=1 pip install .`, and use a call like the one in the [developers notes](https://github.com/21cmfast/21cmFAST/blob/master/docs/notes_for_developers.rst):

```
PYTHONMALLOC=malloc valgrind --tool=memcheck --track-origins=yes --leak-check=full --suppressions=valgrind-suppress-all-but-c.supp python mwe_memory_leak.py
```

Going through the places it notes memory leaks there is: 

1. https://github.com/21cmfast/21cmFAST/blob/9a3575038456b6c76d2ff7d9c90876f1dad87115/src/py21cmfast/src/IonisationBox.c#L453 -- the creation of the FFTW plan, which I guess should be free'd somewhere, but I can't see that it is.
2. https://github.com/21cmfast/21cmFAST/blob/9a3575038456b6c76d2ff7d9c90876f1dad87115/src/py21cmfast/src/GenerateICs.c#L443 -- again, a creation of a FFTW plan which seems not to be freed.
3. https://github.com/21cmfast/21cmFAST/blob/9a3575038456b6c76d2ff7d9c90876f1dad87115/src/py21cmfast/src/GenerateICs.c#L578 -- the same kind of thing again.
4. https://github.com/21cmfast/21cmFAST/blob/9a3575038456b6c76d2ff7d9c90876f1dad87115/src/py21cmfast/src/GenerateICs.c#L344 -- the same thing again.
5. https://github.com/21cmfast/21cmFAST/blob/9a3575038456b6c76d2ff7d9c90876f1dad87115/src/py21cmfast/src/BrightnessTemperatureBox.c#L201 -- same again.
6. https://github.com/21cmfast/21cmFAST/blob/9a3575038456b6c76d2ff7d9c90876f1dad87115/src/py21cmfast/src/BrightnessTemperatureBox.c#L127 -- again.
7. https://github.com/21cmfast/21cmFAST/blob/9a3575038456b6c76d2ff7d9c90876f1dad87115/src/py21cmfast/src/IonisationBox.c#L316 -- again
8. https://github.com/21cmfast/21cmFAST/blob/9a3575038456b6c76d2ff7d9c90876f1dad87115/src/py21cmfast/src/PerturbField.c#L371 -- again
9. https://github.com/21cmfast/21cmFAST/blob/9a3575038456b6c76d2ff7d9c90876f1dad87115/src/py21cmfast/src/PerturbField.c#L288 -- again
10. https://github.com/21cmfast/21cmFAST/blob/9a3575038456b6c76d2ff7d9c90876f1dad87115/src/py21cmfast/src/PerturbField.c#L253 -- again
11. https://github.com/21cmfast/21cmFAST/blob/9a3575038456b6c76d2ff7d9c90876f1dad87115/src/py21cmfast/src/GenerateICs.c#L183 -- again
12. https://github.com/21cmfast/21cmFAST/blob/9a3575038456b6c76d2ff7d9c90876f1dad87115/src/py21cmfast/src/GenerateICs.c#L509 -- again

I don't know much about FFTW plans, but I'm sure @BradGreig has a good idea here.

**Comment by catherinewatkinson** [comment]
I was just about to email re missing fftwf_cleanup();

You have one in IonisationBox, but not in perturb, ICs and brightnessTemp. I've just added them and it seems to be reducing the built up memory...

**Comment by catherinewatkinson** [comment]
I think you need to add the following as well to L830 of IonisationBox as the following are only allocated under these conditions:
if(flag_options->USE_MASS_DEPENDENT_ZETA) {
      free(xi_SFR);
      free(wi_SFR);
    }
    if(INIT_ERFC_INTERPOLATION) {
      free(ERFC_VALS); 
      free(ERFC_VALS_DIFF); 
    }

**Comment by steven-murray** [comment]
Haha, I've just started making these changes as well! Do you want to finish making them in a branch, and push it up so I can run the test again?

One thing: the ERFC_VALS is not meant to be freed -- it is a thing that gets initialised once and then kept for the rest of the session.

**Comment by catherinewatkinson** [comment]
I've made the changes in my branch for updating the density field generation... and I doubt that is ready to merge just yet as I've done it but not tested.

Go ahead and I will just suffer the consequences next time I pull :)

I didn't check the spin temp one or any others as I was not running in spin temp mode. So check the others for fftw_cleanup. 

Re. the ERFC_VALS... Surely it has to be freed at some point? I am definitely no expert, but I was under the impression that if anything is allocated memory in C, then it has to be explicitly freed somewhere in the program before it exits, otherwise that block of memory remains allocated/full? I'm pretty confident this would cause a memory leak.

**Comment by steven-murray** [comment]
Hahaha that's always the way. OK I'll make those changes myself and see what happens. 

So yeah, the ERFC_VALS should be freed right at the end, but since we're in a Python _session_, how do we know the end is? The point is, that is an array that gets allocated only once in any given python session -- it's not memory that's going to build up. 

I could look at an exit hook on python that would try to do some final free'ing before it shuts down, but it's not high on my priority list!

**Comment by ghost** [comment]
If that's the behaviour you want then you should allocate the erfc_vals in python and pass them somehow. Memory allocated in python will look after itself. Any memory allocated in the C code must be explicitly freed at some point. Otherwise you will get a memory leak. At least that's my understanding. You should also be able allocate it in C at a global level and then free it by calling a function. But I am almost 100% certain you need to free that memory in C somewhere.

**Comment by steven-murray** [comment]
Yeah, you're right. However, it really does make sense to allocate this in C. It will be a (small) memory leak at the termination of the program, but nothing huge. We can definitely free it by calling a C function at some point -- I will look into it.

**Comment by catherinewatkinson** [comment]
Just thinking about this some more. I'm not sure I follow why you don't just allocate these and free them on every call like everything else. Can you clarify the logic of this?

**Comment by steven-murray** [comment]
It's just for speed -- these are the same _every time_, so there's no point in initialising them hundred's of times in an MCMC.

**Comment by BradGreig** [comment]
These will be regenerated once each time either run_coeval or run_lightcone are called. It should be possible to then free at the end of run_coeval and run_lightcone equivalent to how the spin temperature boxes are freed (with the free_TsCalcBoxes).

As for the fftwf_cleanup, these did exist at one point but they were causing a segfault so I removed them. It appears I didn't put them back...

If no one has properly advanced this memory issue, I can create a branch that deals with this.

**Comment by steven-murray** [comment]
@BradGreig I've got a branch to deal with it -- I'll push it up shortly so you can review it.

**Comment by steven-murray** [comment]
@BradGreig I was hoping to finish the better-testing branch before getting the memory leak stuff in a state that was more palatable for you. However, that is traveling much more slowly than anticipated, and I have an application to do this week. I've pushed up a `memleak` branch to 21cmFAST (which I'm pretty sure is where the leak is happening), and a `memory-leak` branch here. 

My workflow has been to make changes in the C code, then run the the `devel/mwe_memory_leak.py` script in 21cmMC under valgrind, i.e. (in the `devel` folder):

```
$ PYTHONMALLOC=malloc valgrind --tool=memcheck --track-origins=yes --leak-check=full --suppressions=valgrind-suppress-all-but-c.supp python mwe_memory_leak.py > valgrind.out 2>&1 
```

At the same time, in another terminal, I sometimes run 
```
top -d 0.3 | grep mwe | awk '{ printf("%-8s  %-8s  %-8s  %-8s\n", $4, $5, $8, $9); }' > memory_capture_single_thread.txt 
```
which captures the memory usage as viewed by `top` over time. My last run-through seemed to indicate that some fftw stuff still wasn't being freed properly, so I may not have done it correctly.

**Comment by BradGreig** [comment]
@steven-murray I have started to look into this. To me the fftw cleanups etc. appear to be ok. However, I note a bunch of other arrays etc. that are not explicitly freed (e.g. interpolation tables etc.).

By the way, what are the 4 columns you are outputting? I am on a mac so this doesn't work the same for me, thus would like to be comparing similar things

**Comment by steven-murray** [comment]
Sorry @BradGreig I didn't see your comment til now. I found that doing a `fftwf_destroy_plan(plan);` after every plan execution made the valgrind memory leak errors go away. I've pushed those changes to the `memleak` branch on 21cmFAST. I've also updated the `memory-leak` branch of 21cmMC to use the most up-to-date version of 21cmFAST. 

There is now a script in 21cmFAST in `devel/simulate_mcmc_memory_leak.py` which just performs a bunch of iterations of 21cmFAST, similar to what the MCMC should do, also tracking memory usage. I've run this and it reports that the overall memory usage stays the same between iterations as expected. I've also run again the `devel/mwe_memory_leak.py` script in this repo, both under valgrind and not. It reports no valgrind errors, and also the tracked total memory usage remains constant on my machine. I've also now run the intro MCMC notebook, and it runs through without crashing my computer. 

Can someone else test either the MWE memory leak script, or the tutorial notebook, to see if it works for them? Remember to re-install 21cmFAST from the `memleak` branch (and the `memory-leak` branch from this repo). I'm looking at you, @binnietom and @BradGreig  :-)

**Comment by BradGreig** [comment]
@steven-murray I have just ran this and confirm I didn't see any increase in memory while running this. Further, I increased the number of iterations and saw no notable increase.

A couple of things though. In your fix for the interpolation tables (better-testing branch) you've defined a loop that requires a specific C standard (the skipline function, defining int i within the loop). Given this is not how the rest of the code is written, its probably best not to have this. Otherwise, users will need to be explicit in defining their C environment.

Secondly, the usage of the free_TsCalcBoxes() function causes segfaults. I think this should be a function that is called only once at the end of the run_coeval() and run_lightcone() functions. I agree this will cause issues when either run_coeval() or run_lightcone() are not used with regard to memory freeing/access, however, this behaviour is preferable over the performance hit of having to re-create all the interpolation tables for each individual redshift. Alternatively, you can perhaps keep track of an internal flag that free_TsCalcBoxes() is always initiated, unless run_coeval() or run_lightcone() are called in which case they turn off the usage of free_TsCalcBoxes() to explicitly call it once from python.

**Comment by steven-murray** [comment]
@BradGreig Noted! I'll fix those things -- I was definitely wondering whether the freeing of the TsCalcBoxes was a good idea (though not freeing it caused segfaults for me in a different, corner-case, context). I can certainly get around that though. 

I was also meaning to ask you whether you think destroying all the FFTW plans is really a good idea -- I mean, it "works" in terms of a memory leak, but is there a better, more efficient way? I've heard that you can do some kind of "create many plans" function, but not sure how to use it. 

I also didn't realize that defining `int i` within a loop was standard-specific!

**Comment by BradGreig** [comment]
@steven-murray I don't think there is any issue with destroying the plans after each usage. Its probably overkill, but if it prevents leaks I guess it'll do. There shouldn't be any specific performance cost for doing it.

I wonder if you could define 4 plans, R2C, C2R for DIM and HII_DIM and then destroy each only at the end, rather than after each usage. Might make the code look a little cleaner, but might still cause memory leakage. You can also create arrays of plans.

**Comment by steven-murray** [comment]
From my brief reading around, the plans are attached to arrays, so you can't re-use them on different bits of memory. But I guess if we're using the same bit of memory, and just re-filling it time-after-time with different data, then it will work to re-use them. 

I think it will take careful thought and testing though, so perhaps I'll create an issue for it and we can address it down the line.

**Comment by BradGreig** [comment]
In a lot of instances, we are performing FFTs of the same memory. So it should be able to be minimised. I agree that we can leave this to a later point though as its less critical now it seems to be in a usable format
