### ISSUE TITLE
[BUG] PF being run every iteration

### ISSUE THREAD

**Issue by steven-murray** [21cmfast/21CMMC#42]
**Describe the bug:**

@qyx268 and @catherinewatkinson both report that `perturb_field` is being run every iteration, despite none of the params being cosmological. This would be horrible.

**To Reproduce:**
I will let @catherinewatkinson and/or @qyx268 post steps to reproduce.

**Expected behavior:**

If no cosmological parameters are being changed (only `AstroParams`), then only `spin_temp` and/or `ionize_box` should be re-run on any iteration. The init and perturb field should be computed and stored on disk at the beginning, and read in on every iteration.

**Comment by qyx268** [comment]
I think it only stores `InitialConditions` and one `PerturbedField`. It happened to all my MCMC runs. e.g. 
```
import numpy as np

from py21cmmc import mcmc, analyse
from py21cmmc import Likelihood1DPowerLightcone, CoreLightConeModule
from py21cmmc import LikelihoodLuminosityFunction, CoreLuminosityFunction
from py21cmmc import LikelihoodNeutralFraction

import logging

def function_global_xHI(ctx):
    return ctx.get('lightcone').global_xH

storage = {"global_xHI": function_global_xHI}
user_params = {'HII_DIM':128, 'BOX_LEN':250.0}
#cosmo_params = {'SIGMA_8': 0.8111, 'hlittle': 0.6736, 'OMm': 0.3153, 'OMb':0.04932, 'POWER_INDEX':0.9649}
cosmo_params = {'SIGMA_8': 0.8118, 'hlittle': 0.6688, 'OMm': 0.321, 'OMb':0.04952, 'POWER_INDEX':0.9626}
flag_options = {'USE_MASS_DEPENDENT_ZETA': True, 'INHOMO_RECO': True, 'PHOTON_CONS': False}
global_params = {'Z_HEAT_MAX': 20.0, 'ZPRIME_STEP_FACTOR': 1.02}

model_name = "DarkFraction_LF"

core = [ CoreLightConeModule(redshift=5.0, user_params=user_params, cosmo_params=cosmo_params, flag_options=flag_options, global_params=global_params,
                             regenerate=False,initial_conditions_seed = 1993,cache_dir='./', store=storage),
         CoreLuminosityFunction( redshift=6, sigma=0, name='lfz6', user_params=user_params, cosmo_params=cosmo_params, flag_options=flag_options ),
         CoreLuminosityFunction( redshift=7, sigma=0, name='lfz7', user_params=user_params, cosmo_params=cosmo_params, flag_options=flag_options ),
         CoreLuminosityFunction( redshift=8, sigma=0, name='lfz8', user_params=user_params, cosmo_params=cosmo_params, flag_options=flag_options ),
         CoreLuminosityFunction( redshift=10, sigma=0, name='lfz10', user_params=user_params, cosmo_params=cosmo_params, flag_options=flag_options )]


likelihood = [ LikelihoodNeutralFraction(),
               LikelihoodLuminosityFunction(name='lfz6', simulate = False, ),
               LikelihoodLuminosityFunction(name='lfz7', simulate = False, ),
               LikelihoodLuminosityFunction(name='lfz8', simulate = False, ),
               LikelihoodLuminosityFunction(name='lfz10', simulate = False, )]


chain = mcmc.run_mcmc(
    core, likelihood,        # Use lists if multiple cores/likelihoods required. These will be eval'd in order.
    datadir='./',          # Directory for all outputs
    model_name=model_name,   # Filename of main chain output
    params=dict(             # Parameter dict as described above.
        F_STAR10 = [-1.3, -3, 0, 1.0],
        ALPHA_STAR = [0.5, -0.5, 1.0, 1.0],
        F_ESC10 = [-1, -3, 0, 1.0],
        ALPHA_ESC = [-0.5, -1.0, 0.5, 1.0],
        M_TURN = [8.69897, 8, 10, 1.0],
        t_STAR = [0.5, 0.01, 1, 0.5],
    ),
    walkersRatio=100,
    burninIterations=5,
    sampleIterations=250,
    threadCount=60,
    continue_sampling=True,  # Whether to contine sampling from previous run *up to* sampleIterations.
)
```

However, I cannot be sure if after (re)starting, whether it will calculate all `PerturbedField` once and store them in the RAM for other iterations or it will indeed recalculate `PerturbedField` at each iteration. I will use logging to see what's happening.

**Comment by qyx268** [comment]
You can see in [log1.txt](https://github.com/21cmfast/21CMMC/files/4882682/log1.txt) that `PerturbField.c` is run at every redshift for each iteration (this is run with similar setup as shown above)

You can also see in [log.txt](https://github.com/21cmfast/21CMMC/files/4882680/log.txt) that when `cache_mcmc=True`, `PerturbField.c` is run at every redshift only for the first iteration. 

These are all done with `threadCount=1`

A temporary fix will be to set `threadCount=1` and `cache_mcmc=True` to output all `PerturbedField` and then restart with `threadCount=N(needed)` and `cache_mcmc=False`.

**Comment by steven-murray** [comment]
Ahhhh, OK, I think I know what's happening. 

For a set of Coeval boxes, it should work as expected, since the `PerturbField` is initialized and stored at each desired redshift. However, for Lightcones, the `PerturbedField` is only stored for the final redshift, and all the other redshifts throughout the evolution are then computed every time (because through the MCMC, boxes are not stored). 

I think the easiest way around this is to save the _full_ Coeval/Lightcone at the fiducial parameters for the initialization. This will use a bit more disk space than is perhaps absolutely necessary, but realistically, the fiducial set of data is probably useful after the MCMC anyway.
