### ISSUE TITLE
[BUG] pymultinest: strange likelihood values for failed 21cmFAST parameters

### ISSUE THREAD

**Issue by dprelogo** [21cmfast/21CMMC#61]
**Describe the bug:**

Running 21CMMC with `pymultinest` makes a weird output for the failed 21cmFAST parameter values. Instead of `-inf`, it saves a small positive number for the likelihood, which makes the run completely biased to that region. 

I'm attaching a sample output for the [post_equal_weight](https://github.com/21cmfast/21CMMC/files/8686289/post_equal_weight.txt) file. The items with likelihood `0.467...-309` have parameter values equal to the failed 21cmFAST runs.

The same run with `emcee` behaves normally.

**Expected behavior:**
For failed runs a large negative log-likelihood values should be outputted. I suspect this is the problem of how `pymultinest` interprets `np.inf`. Maybe just a large float number would suffice.

**Comment by steven-murray** [comment]
When using `polychord`, which is roughly the same, I have this in my log posterior:

![image](https://user-images.githubusercontent.com/1272030/168336925-fa797766-0157-4e46-9dfc-c31246ab3f7e.png)

I think the `np.nan_to_num` might be what we want.

**Comment by qyx268** [comment]
yeah, I have had this issue for a very long time. I couldn't find a good solution. So I had to record the progress with git and checkout back to earlier commits when this happens. 

I assumed it was due to how fortran writes stuffs. I thought those lines with e.g. `0.467...-309` were supposed to be 0.467...e-309, but somehow, it omitted the "E" during writing. But maybe you are right, it is just how fortran writes NaN. If this is the case, @steven-murray 's hack should solve the issue. @dprelogo  could you give it a try?

**Comment by dprelogo** [comment]
Thanks for the tips, this is a cool trick @steven-murray! I wrote a patch that allows user to pick behaviour... if the test runs finish fine, I'll create a PR.

**Comment by dprelogo** [comment]
Here are the observations of the test runs...
If I understood correctly, the part of code which should control what happen in the case of `ParameterError` is the following [line](https://github.com/21cmfast/21CMMC/blob/a29145c2176945ffbdadfc029258f07d1de05403/src/py21cmmc/cosmoHammer.py#L684). I investigated two scenarios:
- putting some other large negative value instead of `-np.inf` (`-1e+30`, `-1e+300`, `-0.99 * np.nan_to_num(np.inf)`), with `ParameterError` raised for some parameter values in the likelihood
- controlling `ParameterError` directly in the likelihood and putting some large negative value if there's an error (including `-np.inf`)

All runs in the first scenario failed, and all in the second behaved well. It seems that the likelihood function implemented in run_mcmc ([here](https://github.com/21cmfast/21CMMC/blob/a29145c2176945ffbdadfc029258f07d1de05403/src/py21cmmc/mcmc.py#L210)) doesn't make a call and catch `ParameterError`.

I tried to replace it with the following function:
```
def likelihood(p, ndim, nparams):
    inp = [
        params[i][1] + p[i] * (params[i][2] - params[i][1]) for i in range(ndim)
    ]
    lnl, data = chain(inp)
    return lnl
```
This solves the issue completely, but the code is an order of magnitude slower. This is for a very simple likelihood, where the full code takes a few seconds, so maybe in realistic scenario overhead wouldn't be so much.
I'll test this further, but could you tell if such function makes sense, or it calculates something unnecessary with respect to the current one?

**Comment by qyx268** [comment]
I added that part. I didn't want to rebuild the chain because I had concerns that it might add existing likelihood again (which could be the reason that it is getting a bit slower?) and therefore double count. 

I wonder if you could simply do 
```
try:
    return chain.computeLikelihoods(
                chain.build_model_data(
                    Params(*[(k, v) for k, v in zip(params.keys, inp)])
                )
    except ParameterError:
        return -np.inf


```

**Comment by dprelogo** [comment]
#62

**Comment by dprelogo** [comment]
I'm not 100% what exactly is an overhead. However, this seems like a reasonable solution... 
I tested it and it works properly.

**Comment by steven-murray** [comment]
I'm not sure exactly what's going on here. First, it isn't clear to me that `-inf` is returned only when there's a `ParameterError`... there are valid parameters (physically) that might still be outside their prior range. To me, the solution would be to change the likelihood you linked above to 

```python
def likelihood(p, ndim, nparams):
    lnl = chain.computeLikelihoods(
        chain.build_model_data(p)
    ) 
    return max(lnl, np.nan_to_num(-np.inf))
```

Does that not work? Also, note that the `prior` function [here](https://github.com/21cmfast/21CMMC/blob/a29145c2176945ffbdadfc029258f07d1de05403/src/py21cmmc/mcmc.py#L220) doesn't do anything, i.e. it doesn't return anything.

The code that you have -- is it trying to rescale the parameters to be within their prior? Kind of like sampling from a unit hypercube?

**Comment by qyx268** [comment]
... I kept replying to the wrong thread

> yes, that's right. It is all because multinest samples in unit hypercube, so I need to rescale them back to run the model and also I use this `run` function from `pymultinest` which has its own way of taking prior and likelihood as inputs.
